-- =============================================================================
-- Sagentics WhatsApp – full schema for a fresh Supabase project
-- Run this entire file in Supabase SQL Editor (or run migrations 001–006 in order).
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. WhatsApp tables: chatbot_history, whatsapp_human_control
-- -----------------------------------------------------------------------------
-- chatbot_history: every message (incoming + outgoing) for dashboard and AI context
create table if not exists public.chatbot_history (
  id bigint generated by default as identity primary key,
  session_id text not null,
  message jsonb not null,
  customer jsonb not null,
  date_time timestamptz not null default now()
);

create index if not exists idx_chatbot_history_session_id on public.chatbot_history (session_id);
create index if not exists idx_chatbot_history_date_time on public.chatbot_history (date_time);

comment on table public.chatbot_history is 'Stores every message (human and AI) for dashboard and AI context. message: { type: "human"|"ai", content: string }. customer: { number: string, name?: string }.';

-- whatsapp_human_control: which conversations are in human takeover (AI must not reply)
create table if not exists public.whatsapp_human_control (
  session_id text primary key,
  is_human_controlled boolean not null,
  updated_at timestamptz default now()
);

comment on table public.whatsapp_human_control is 'When is_human_controlled = true, AI must not reply to that session.';

-- -----------------------------------------------------------------------------
-- 2. View: chatbot_history_flat (normalizes message/customer for reads)
-- -----------------------------------------------------------------------------
create or replace view public.chatbot_history_flat as
select
  id,
  session_id,
  date_time,
  coalesce(message->>'type', (message#>>'{}')::jsonb->>'type') as msg_type,
  coalesce(message->>'content', (message#>>'{}')::jsonb->>'content') as msg_content,
  coalesce(message->>'body', (message#>>'{}')::jsonb->>'body') as msg_body,
  coalesce(customer->>'name', (customer#>>'{}')::jsonb->>'name') as cust_name,
  coalesce(customer->>'number', (customer#>>'{}')::jsonb->>'number') as cust_number
from public.chatbot_history;

-- -----------------------------------------------------------------------------
-- 3. App settings (key-value for WhatsApp AI mode, whitelist, system prompt)
-- -----------------------------------------------------------------------------
create table if not exists public.app_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz default now()
);

comment on table public.app_settings is 'App-wide settings. key e.g. whatsapp_ai, value e.g. { "devMode": true, "allowedNumbers": ["27693475825"], "systemPrompt": "...", "model": "gpt-4o-mini" }.';

-- -----------------------------------------------------------------------------
-- 4. Knowledge base (RAG: chunks + embeddings + match function)
-- -----------------------------------------------------------------------------
create extension if not exists vector;

create table if not exists public.knowledge_base (
  id bigint generated by default as identity primary key,
  source text not null,
  content text not null,
  embedding vector(1536) not null,
  metadata jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_knowledge_base_embedding on public.knowledge_base
  using hnsw (embedding vector_cosine_ops)
  with (m = 16, ef_construction = 64);

create index if not exists idx_knowledge_base_source on public.knowledge_base (source);

comment on table public.knowledge_base is 'Chunks of text with embeddings for RAG. source e.g. FAQ, content = chunk text, embedding from OpenAI text-embedding-3-small.';

-- RPC: return top match_count rows by cosine similarity to query_embedding
create or replace function public.match_knowledge(
  query_embedding vector(1536),
  match_count int default 5
)
returns table (
  id bigint,
  source text,
  content text,
  similarity float
)
language sql stable
as $$
  select
    knowledge_base.id,
    knowledge_base.source,
    knowledge_base.content,
    1 - (knowledge_base.embedding <=> query_embedding) as similarity
  from public.knowledge_base
  order by knowledge_base.embedding <=> query_embedding
  limit match_count;
$$;

-- -----------------------------------------------------------------------------
-- 5. Inactivity alert log (throttle emails)
-- -----------------------------------------------------------------------------
create table if not exists public.inactivity_alert_log (
  id bigint generated by default as identity primary key,
  sent_at timestamptz not null default now()
);

create index if not exists idx_inactivity_alert_log_sent_at on public.inactivity_alert_log (sent_at desc);

comment on table public.inactivity_alert_log is 'Throttle: one row per inactivity email sent; used to avoid sending more than one alert per 4 hours.';

-- -----------------------------------------------------------------------------
-- 6. Realtime: broadcast INSERTs on chatbot_history for live messages
-- -----------------------------------------------------------------------------
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'chatbot_history'
  ) then
    alter publication supabase_realtime add table public.chatbot_history;
  end if;
end $$;
