-- Log when we send an inactivity alert so we don't spam (at most one email per 4 hours).
create table if not exists inactivity_alert_log (
  id bigint generated by default as identity primary key,
  sent_at timestamptz not null default now()
);

create index if not exists idx_inactivity_alert_log_sent_at on inactivity_alert_log (sent_at desc);

comment on table inactivity_alert_log is 'Throttle: one row per inactivity email sent; used to avoid sending more than one alert per 4 hours.';
