-- Stores WhatsApp Business accounts connected via Meta Embedded Signup.
-- The app reads phone_number_id and access_token from here (falls back to env vars).
create table if not exists public.whatsapp_connections (
  id bigint generated by default as identity primary key,
  waba_id text not null,
  phone_number_id text not null,
  access_token text not null,
  display_phone_number text,
  display_name text,
  connected_at timestamptz not null default now(),
  connected_by uuid references auth.users(id)
);

create unique index if not exists idx_whatsapp_connections_phone on public.whatsapp_connections (phone_number_id);

comment on table public.whatsapp_connections is 'WhatsApp Business accounts connected via Meta Embedded Signup. Stores access_token and phone_number_id for sending messages.';
